name: Privileges
main: net.krinsoft.privileges.Privileges
author: krinsdeath
version: maven-version-number
load: startup

commands:
  privileges:
    aliases:
      - priv
      # /priv check
      - pc
      # /priv list
      - plist
      # /priv group*
      - pg
      - pgp
      # /priv user*
      - pu
      - pup
    description: The commands for manipulating player permissions
    usage: /<command> [section] [options]...
  plist:
    description: Lists all nodes for the specified user.
    permission: privileges.list
    usage: /<command> [player] [page]
  pinfo:
    aliases: [pi]
    description: Shows miscellaneous info about the given user
    permission: privileges.info
    usage: /<command> [player]
  promote:
    description: Promotes the specified player to the next higher rank
    permission: privileges.promote
    usage: /<command> [player]
  demote:
    description: Demotes the specified player to the next lowest rank
    permission: privileges.demote
    usage: /<command> [player]
  pgl:
    description: Lists all available groups.
    permission: privileges.group.list
    usage: /<command>
  pgs:
    description: Sets the specified player's group
    permission: privileges.group.set
    usage: /<command> [player] [group]
  pgr:
    description: Removes the specified group
    permission: privileges.group.remove
    usage: /<command> [group] --safe
  pgc:
    description: Creates the specified group with the given rank
    permission: privileges.group.create
    usage: /<command> [group] [rank]
  pgps:
    description: Sets the specified permission for the given group
    permission: privileges.group.perm.set
    usage: /<command> [group] [node] [true|false]
  pgpr:
    description: Removes the specified permission from the given group
    permission: privileges.group.perm.remove
    usage: /<command> [group] [node]
  pupr:
    description: Removes the specified permission from the given user
    permission: privileges.user.perm.remove
    usage: /<command> [player] [node]
  pups:
    description: Sets the specified permission for the given user
    permission: privileges.user.perm.set
    usage: /<command> [player] [node] [true|false]
  help:
    aliases: [h]
    description: Displays help for available commands
    permission: privileges.help
    usage: /<command> [page]
permissions:
  privileges.build:
    description: Determines whether or not a player can build.
    default: true
  privileges.interact:
    description: Determines whether or not a player can interact with the game objects.
    default: true
  privileges.list.other:
    description: Allows viewing other peoples permissions node lists.
  privileges.check.other:
    description: Allows checking whether a node is set on another user.
  privileges.self.edit:
    description: Allows any user with this node to edit any permission they want, regardless of rank.
    default: false
  privileges.restricted:
    description: A set of nodes that restrict a user from interacting and building
    children:
      privileges.build: false
      privileges.interact: false
  privileges.users:
    description: A set of nodes for the typical user
    children:
      privileges.build: true
      privileges.check: true
      privileges.help: true
      privileges.info: true
      privileges.interact: true
      privileges.list: true
      privileges.version: true
  privileges.mods:
    description: A set of nodes useful for a typical moderator
    children:
      privileges.check.other: true
      privileges.debug: true
      privileges.group.list: true
      privileges.info.other: true
      privileges.list.other: true
      privileges.promote: true
      privileges.reload: true
  privileges.admins:
    description: Sets all user and group permission editing nodes.
    children:
      privileges.group.*: true
      privileges.user.*: true