name: Privileges
main: net.krinsoft.privileges.Privileges
author: krinsdeath
version: maven-version-number
load: startup

commands:
  privileges:
    aliases:
      # /priv *
      - priv
      # /priv reload
      - pr
      # /priv check
      - pc
      # /priv debug
      - pd
      # /priv group*
      - pg
      - pgc
      - pgr
      - pgs
      # /priv group perm*
      - pgp
      - pgps
      - pgpr
      # /priv user*
      - pu
      # /priv user perm*
      - pup
      - pups
      - pupr
    description: The commands for manipulating players and settings
    usage: /<command>

permissions:
  privileges.build:
    description: Determines whether or not a player can build.
    default: true
  privileges.interact:
    description: Determines whether or not a player can interact with the game objects.
    default: true