name: Privileges
main: net.krinsoft.privileges.Privileges
author: krinsdeath
version: ${project.version}-b${project.build.number}

commands:
  privileges:
    aliases:
      # /priv *
      - priv
      # /priv reload
      - pr
      # /priv check
      - pc
      # /priv group*
      - pg
      - pgc
      - pgr
      - pgp
      - pgps
      - pgpr
    description: The commands for manipulating players and settings
    usage: |